### ISSUE TITLE
"www" Stripped From Absolute Urls with Minimize

### ISSUE THREAD

**Issue by jspears** [webpack/css-loader#104]
When minimize is turned on it seems to remove the www from urls.

I have a little project demonstrating the problem.

https://github.com/jspears/css-loader-minimize-issue.git

Thanks!
-Justin

**Comment by joezimjs** [comment]
I just ran your example and the www was still there. Did you try with latest versions?

**Comment by d3viant0ne** [comment]
If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this  one.
