### ISSUE TITLE
"class-1" classes not working 

### ISSUE THREAD

**Issue by Nico-Echezarreta** [webpack/css-loader#109]
I have some classes (class-1, class-10) which are not working when the hash is applied. 
It doest work without the [hash] option in the identLocalName and you just use [name]__[local].
Ex: the class is "bar-1".
      The class name after being parsed is FilterResults-local__bar__2ObzC-1

The "-1" is appended to the end of the class name so it doesnt apply any styles.

**Comment by sokra** [comment]
Do you use the lastest css-loader version?

**Comment by Nico-Echezarreta** [comment]
Yeah, I'm using 0.15.4.

**Comment by sokra** [comment]
cannot reproduce it... Try to `npm update` all dependencies of css-loader.

**Comment by Nico-Echezarreta** [comment]
this is my css loader conf

loader: 'style-loader!css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]__[hash:base64:5]!postcss-loader'
