### ISSUE TITLE
incorrect export of locals

### ISSUE THREAD

**Issue by Coobaha** [webpack/css-loader#112]
if there is a `ch` in local class like: `:local .gсh`  - loader will strip all after `ch`, 
so {g: 'generatedClassName'} will be exported
strange stuff.. :)
```
:local(.withSearсhButton)
  :local(.allOptions)
    display none

:local(.withSearсhButton)
  color red


:local(.сhButton)
  color green
```

outputs
`Object {withSear: "app-main-components-SearchBar-gg---withSear---psEQw", allOptions: "app-main-components-SearchBar-gg---allOptions---1UsCx"}`

config:

`css-loader?minimize=false&localIdentName=[path][name]---[local]---[hash:base64:5]`

tried versions 0.15.3, 0.15.5

**Comment by sokra** [comment]
I first thought: what a weird issue... And I could reproduce it when copying your `.withSearсhButton` class, but it's fine when I type `.withSearchButton` ;).

The solution: Your `с` is not an ASCII `c`. It just looks like one... No idea how you typed it, but try to use the `c` key of your keyboard instead :smile: 

``` js
"с".charCodeAt(0)
> 1089
"c".charCodeAt(0)
> 99
```

**Comment by Coobaha** [comment]
oh, this is some IDE bug imo, i typed a lot of variants. This is russian C, he-he.
thanks :)
