### ISSUE TITLE
Stacked backgrounds are over-optimized (0.14.5) after uglifying with webpack

### ISSUE THREAD

**Issue by MalcolmDwyer** [webpack/css-loader#119]
```
.classA {
  background: #1e5799;
  background: linear-gradient(to right,#7db9e8 10%,#2989d8 50%,#1e5799 100%),#1e5799;
}

.classB {
  background: #1e5799;
}
```

The first background is given in classA as a fallback for old browsers.  (This is a trimmed version... the real version I'm using is like this: http://www.colorzilla.com/gradient-editor/#7db9e8+10,2989d8+50,1e5799+100 )

With that matching color in classB, it outputs as:

```
.classA {
  background: linear-gradient(to right,#7db9e8 10%,#2989d8 50%,#1e5799 100%),#1e5799;
}
.classA, .classB {
  background: #1e5799;
}
```

ClassA is now underspecified and due to ordering of the classes, the browser uses the flat background color for .classA and applies it, overriding the gradient in .classA.

My setup... (I'm not sure what's relevant)

```
    loaders: [
      {
        test: path.join(__dirname, 'app/js'),
        loader: 'babel-loader'
      },
      {
        // test: path.join(__dirname, 'app/style'),
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }
```

My dev build with webpack keeps the original CSS and it works fine, but when I do the production webpack build with `UglifyJsPlugin({compress:{warnings: false}})`, then then minified CSS has the problem above.
-Thanks

**Comment by MalcolmDwyer** [comment]
By the way, my workaround is to just slightly change that fallback color in class A so that it no longer matches the one in B.  Still... I assume stacking of properties for old-browser fallback should be possible, so this doesn't look like correct behavior.

**Comment by alexlande** [comment]
@MalcolmDwyer: Minification is handled by clean-css, which can be pretty destructive to your minified CSS. Disabling some of the more advanced options in clean-css as described here might help: https://github.com/webpack/css-loader#minification
