### ISSUE TITLE
inline fonts does not work in release mode

### ISSUE THREAD

**Issue by debdattabasu** [webpack/css-loader#120]
I have a font definition: 

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local("Material Icons"), 
    local("MaterialIcons-Regular"), 
    url("data:application/x-font-woff;base64,d09G........") format("woff");
}

This works in debug mode but not in release mode with the -p flag in latest version. Last known version to work was 0.14.4. Reverted to that for now.

**Comment by dax0** [comment]
I'm also seeing this issue.  It looks like the Uglify plugin is stripping out font-face completely. Not sure how it works on CSS

**Comment by sambou** [comment]
Does anybody know of a fix for this?

**Comment by d3viant0ne** [comment]
If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this  one.
