### ISSUE TITLE
Escaped characters in CSS content are not respected

### ISSUE THREAD

**Issue by chandlervdw** [webpack/css-loader#133]
Even though this was listed in #87 and supposedly fixed by https://github.com/css-modules/css-selector-tokenizer/commit/5aa6180c27e1444d4f9601ec5f7ad6b3e894b587, I'm still having this issue.

`content: "\A";` is compiled to `content: "A";`, so the `\` character isn't being parsed correctly...

**Comment by chandlervdw** [comment]
@andreypopp @JackVCurtis @mathieumg are any of you still able to reproduce this issue?

**Comment by chandlervdw** [comment]
I have no idea why this worked but putting ```content: '\"\A';``` fixed it. It outputs as ```content: '\"\A';``` but somehow still renders as a line break. I'm sure this will break soon...

**Comment by chandlervdw** [comment]
Ok, nevermind, that does NOT work.

**Comment by robmcguinness** [comment]
`content: '\0000a0';` is being converted to `content: 'A 0';`.  Downgrading to `v0.14.5` fixes the issue for me.

**Comment by chandlervdw** [comment]
Any word on this? I hate keeping this lib at `v0.14.5`.

**Comment by robmcguinness** [comment]
@chandlervdw my workaround was to alter content value to work with `v0.14.5`+

![image](https://cloud.githubusercontent.com/assets/281070/12646543/bac9cd94-c59e-11e5-84bc-f8a1db9e889e.png)

**Comment by chandlervdw** [comment]
@robmcguinness I'm trying to achieve an end value of `\A` ... can you advise me on what I should change my content value to?

**Comment by robmcguinness** [comment]
@chandlervdw I haven't dug into the code in a while but if I get a minute i'll take a peek

**Comment by pieter** [comment]
Traced the problem to https://github.com/css-modules/css-selector-tokenizer/issues/12

**Comment by h6ah4i** [comment]
+1

**Comment by kencana-voilaah** [comment]
hi guys, encountering same issue, any tweak i should do to make it work for now?

**Comment by tadjohnston** [comment]
Added a PR to bump the`css-selector-tokenizer` version to `0.6.0`.
