### ISSUE TITLE
PostCSS 5.0

### ISSUE THREAD

**Issue by hh9527** [webpack/css-loader#135]
When will this loader update to use PostCSS 5.0?

**Comment by Qrysto** [comment]
+1. I've just got an error because PostCSS uses postcss@4.1.16 and it conflicts with other packages that uses postcss@5.0.4, so I had to use a hack to get it running. Need to be updated ASAP!

**Comment by timdorr** [comment]
Requires #95 being addressed.

**Comment by sokra** [comment]
done

**Comment by hh9527** [comment]
Still has warnings:
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
```

**Comment by sokra** [comment]
these are from dependencies... I take care soon...

**Comment by jedmao** [comment]
@sokra can you re-open this issue until the deprecation warnings are resolved?

cssnano@3.0.0 now supports PostCSS 5.0, but there are 3 dependencies that have yet to support it, for which I have opened PRs:
- https://github.com/css-modules/postcss-modules-extract-imports/issues/8
- https://github.com/css-modules/postcss-modules-local-by-default/issues/28
- https://github.com/css-modules/postcss-modules-scope/issues/18

**Comment by jedmao** [comment]
@sokra any updates on publishing this on npm?

**Comment by sokra** [comment]
Waiting for @geelen to add me as collaborator on npm...

**Comment by dwmkerr** [comment]
+1

**Comment by hh9527** [comment]
+1

**Comment by sokra** [comment]
https://github.com/webpack/css-loader/commit/16528d5616292fcfbdf716025dbefa057cb3ae34
