### ISSUE TITLE
Warning "Container#eachAtRule is deprecated" After update to 0.18.0

### ISSUE THREAD

**Issue by fenivana** [webpack/css-loader#136]
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by LeoAJ** [comment]
+ 1

**Comment by vn38minhtran** [comment]
It is warning of `postcss`.
https://github.com/css-modules/postcss-modules-extract-imports/pull/6
https://github.com/css-modules/postcss-modules-scope/pull/17
https://github.com/css-modules/postcss-modules-local-by-default/pull/27

**Comment by just-boris** [comment]
It is so bothering to see it in the output with any way to remove them.
I see that source code already has alias for that rules: https://github.com/webpack/css-loader/blob/master/lib/processCss.js#L35

Maybe it worth revert condition and use deprecated rule as fallback?

**Comment by veeracs** [comment]
+1

**Comment by just-boris** [comment]
Well, we need to wait until plugins mentioned by @vn38minhtran will have got a new version

**Comment by ljconde** [comment]
+1

**Comment by Lacerda** [comment]
+1

**Comment by canvaskisa** [comment]
+1

**Comment by goncalvesjoao** [comment]
+1

**Comment by goncalvesjoao** [comment]
my bad. just deleted node_modules and ran npm install again and the warning are gone!
Guys, just update css-loader to ^0.19.0 and this issue seems to be closed.

**Comment by ljconde** [comment]
@goncalvesjoao is right. Issue is fixed in 0.19.0.

**Comment by Lacerda** [comment]
yep @goncalvesjoao is right. It's fixed in 0.19.0. :)

**Comment by thisiskylierose** [comment]
Updated to 19 and the warnings still appear.

**Comment by axelson** [comment]
Is there a way to be sure which loader is generating a given error message?

**Comment by galeano** [comment]
+1. I'm running 0.19.0 and I see these warnings. Is it possible it's not css-loader after all?

**Comment by thisiskylierose** [comment]
It's some of the dependencies css-loader uses. If I get time, I will have a look and create a pull request.

**Comment by fxmaxvl** [comment]
After updates -  css-loader to 0.19 and nodejs to last stable version - problem disappeared

**Comment by sokra** [comment]
fixed

**Comment by sc0ttyd** [comment]
This has just started showing up for me, after not seeing those warnings before, after changing to Yarn, with css-loader ^0.23 in my package.json

**Comment by cycleseven** [comment]
I was seeing these same warnings. Turns out `css-loader` wasn't the culprit in my case, it was actually an outdated version of `autoprefixer-loader`. Might be helpful knowledge for somebody out there!

**Comment by michael-ciniawsky** [comment]
@cycleseven Don't use `autoprefixer-loader` it is 'unofficial' without guaranteed support => `postcss-loader` + autoprefixer is the recommended way

**Comment by duhaime** [comment]
I removed `autoprefix-loader` from `package.json` and my webpack.config file, then updated css loader to: `css-loader": "^0.28.9` and all was well.
