### ISSUE TITLE
First webpack run includes css-base.js

### ISSUE THREAD

**Issue by giannico** [webpack/css-loader#142]
I'm noticing that during my first webpack run (in dev mode/watch mode), one of my output assets (a vendor module, to be specific) contains the following code as the end of the file:

`
,45:function(module,exports){eval('/*\r\n   MIT License http://www.opensource.org/licenses/mit-license.php\r\n  Author Tobias Koppers @sokra\r\n*/\r\n// css base code, injected by the css-loader\r\nmodule.exports = function() {\r\n var list = [];\r\n\r\n  // return the list of modules as css string\r\n list.toString = function toString() {\r\n       var result = [];\r\n        for(var i = 0; i < this.length; i++) {\r\n          var item = this[i];\r\n         if(item[2]) {\r\n               result.push("@media " + item[2] + "{" + item[1] + "}");\r\n         } else {\r\n                result.push(item[1]);\r\n           }\r\n       }\r\n       return result.join("");\r\n };\r\n\r\n  // import a list of modules into the list\r\n   list.i = function(modules, mediaQuery) {\r\n        if(typeof modules === "string")\r\n         modules = [[null, modules, ""]];\r\n        var alreadyImportedModules = {};\r\n        for(var i = 0; i < this.length; i++) {\r\n          var id = this[i][0];\r\n            if(typeof id === "number")\r\n              alreadyImportedModules[id] = true;\r\n      }\r\n       for(i = 0; i < modules.length; i++) {\r\n           var item = modules[i];\r\n          // skip already imported module\r\n         // this implementation is not 100% perfect for weird media query combinations\r\n           //  when a module is imported multiple times with different media queries.\r\n          //  I hope this will never occur (Hey this way we have smaller bundles)\r\n         if(typeof item[0] !== "number" || !alreadyImportedModules[item[0]]) {\r\n               if(mediaQuery && !item[2]) {\r\n                    item[2] = mediaQuery;\r\n               } else if(mediaQuery) {\r\n                 item[2] = "(" + item[2] + ") and (" + mediaQuery + ")";\r\n             }\r\n               list.push(item);\r\n            }\r\n       }\r\n   };\r\n  return list;\r\n};\r\n\n\n/*****************\n ** WEBPACK FOOTER\n ** ./~/css-loader/lib/css-base.js\n ** module id = 45\n ** module chunks = 0\n **/\n//# sourceURL=webpack:///./~/css-loader/lib/css-base.js?')}});
`

When the 2nd webpack run gets triggered, this block is removed (and seemingly never gets reintroduced). Is this code required in the bundle?

**Comment by d3viant0ne** [comment]
If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this  one.
