### ISSUE TITLE
css-loader 0.19.0 broken due to postcss5 using es6

### ISSUE THREAD

**Issue by istr** [webpack/css-loader#147]
Broken, see [my commit comment](https://github.com/webpack/css-loader/commit/16528d5616292fcfbdf716025dbefa057cb3ae34#commitcomment-13435489).

**Comment by ben-eb** [comment]
Fixed in 5.0.8.

https://github.com/postcss/postcss/issues/582

**Comment by nkbt** [comment]
As a temporary solution add 
```js
require('babel/polyfill');
```

to your build config.

This worked for me well: https://github.com/in-flux/component-router/commit/031006d1f382f29cfee64b1e1c0b4bed3d784921
