### ISSUE TITLE
Class composition not loading

### ISSUE THREAD

**Issue by jasonsilberman** [webpack/css-loader#148]
Hi,

I am getting setup using `css-loader` to enable CSS Modules. However, the file that gets served to the browser still contains the `compose: ...` code.

ie. this is what I get when I look at the CSS being served to the browser.
```
.item-count__label___1fSMp {
  compose: spanNormal;

  margin-bottom: 25px;

  text-transform: lowercase;
  font-style: italic;
  font-size: 90%;
  line-height: normal;
  
  compose: lightTextColor from "../shared/colors.css";
}
```

What could be causing `css-loader` to not replace the `compose` code with the code from the external file?

Thanks,
Jason

**Comment by andreypopp** [comment]
You should write `composes` instead of `compose` as per docs.

**Comment by jasonsilberman** [comment]
Oh wow. I really should have read that closer...
