### ISSUE TITLE
[SUPPORT] how do i minimize with safe mode?

### ISSUE THREAD

**Issue by jonathanong** [webpack/css-loader#156]
seems like css-loader minifies per file, which completely messes up my CSS. i don't see any options supported, and i want it to work w/ and w/o the extract text plugin. anyone have any ideas?

ideally, it would only minify the final builds but that's besides the point

**Comment by QiV** [comment]
+1

**Comment by ianwalter** [comment]
@jonathanong Are you saying the `-minimize` query option doesn't work for you? I can't get it working either.

**Comment by jonathanong** [comment]
i don't remember what happened before, but i use postcss-loader and minify with that using `cssnano` w/ `safe: true` so i no longer run into this issue

**Comment by joebell93** [comment]
Why is this issue closed? The "solution" doesn't seem to solve the underlying issue of using the `minimize` options successfully

**Comment by bebraw** [comment]
@joebell93 Can you re-open with the information the current issue template expects?

**Comment by joebell93** [comment]
@bebraw will do, cheers
