### ISSUE TITLE
Debugging with :local classes

### ISSUE THREAD

**Issue by kevinsimper** [webpack/css-loader#161]
I searched issues and the readme, but could not find any information on how to enable debug, so the class names does not get obfuscated.

This will make it a bit easier to debug.

Thanks for this awesome project!

**Comment by sokra** [comment]
from README:

> You can configure the generated ident with the localIdentName query parameter (default [hash:base64]). Example: css-loader?localIdentName=[path][name]---[local]---[hash:base64:5] for easier debugging.
