### ISSUE TITLE
Getting final css styles from html templates (a static context) 

### ISSUE THREAD

**Issue by prasannavl** [webpack/css-loader#174]
Is there any way to get the generated style names (especially when used with css modules), outside of the regular context?

Use case: 
- Using HtmlWebpackPlugin that runs lodash template loader to parse the html files. The styles names to be directly used in the template in scenarios where you can't wait for javascript.

**Comment by d3viant0ne** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support though you may also inquire in [Webpack Gitter](https://gitter.im/webpack/webpack). The issue tracker is for bug reports and feature discussions. See also our CONTRIBUTING guidelines.
