### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/css-loader/index.js 

### ISSUE THREAD

**Issue by PeterMK85** [webpack/css-loader#180]
New to webpack but after several tries I can't manage css-loader to work.

For example I want to use, this example:
https://github.com/ShMcK/WebpackAngularDemos/tree/master/Part3

And after try to run webpack I receive several errors, related to css-loader & style-loader, every other loader seems to be working fine.

ERROR in ./core/nav/nav.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/css-loader/index.js in C:\xampp\htdocs\webpack/app\core\nav
 @ ./core/nav/nav.scss 4:14-126 13:2-17:4 14:20-132

Enviroment:
- Tested on two separate environments:
- Windows 10Pro & 8.1 Pro
- npm 3.3.10
- node 4.2.1

**Comment by Duan112358** [comment]
I also has this issues

**Comment by BelirafoN** [comment]
I also has this issues

**Comment by opendivision** [comment]
Same issues for me.
https://github.com/opendivision/React-ES6-Boilerplate

Tried "--save", "--save-dev", but no change.

**Comment by salexch** [comment]
change APP = __dirname + '/app'; to var APP = path.resolve(__dirname, 'app')

**Comment by PaulDapolito** [comment]
I am experiencing the same issues:

Windows 10 Pro
npm 2.14.12
node 4.3.0

**Comment by bharatpatil** [comment]
For me in Windows 8.1 inside webpack.config.js after doing following change solved issue above:
context: path.resolve(__dirname, 'app')

**Comment by unreadable** [comment]
@bharatpatil Thank you, this works for me.
I have windows environment.

**Comment by L3V147H4N** [comment]
:+1:

**Comment by pre1ude** [comment]
@bharatpatil Thank you, this works for me.
