### ISSUE TITLE
Scoping @import

### ISSUE THREAD

**Issue by jiku** [webpack/css-loader#181]
I have a (React) component loaded through Webpack whose CSS includes

`@import 'basscss';`

Which then applies Basscss to the whole app. Is there some way to limit it to the component's local scope?

**Comment by vramana** [comment]
@jiku I think you have webcomponents to scope css to a particular DOM element. Any @import declaration just throws it css global namespace. I don't think there any easy to use solutions for this problem.

**Comment by d3viant0ne** [comment]
imo the easy solution to this is to not`@import 'basscss';` Any scoping beyond that should really be handled by your component & react. All of these frameworks are at their heart designed to facilitate small reusable components, global styles have no business there.
