### ISSUE TITLE
CSS sourcemaps have strange repeated paths depending on loaders

### ISSUE THREAD

**Issue by danauclair** [webpack/css-loader#194]
When chaining the autoprefixer-loader and sass-loader I'm seeing strange paths in my resulting sourcemap. Removing the autoprefixer-loader from my config seems to fix the problem, so I'm not sure if this is an issue with the css-loader or autoprefixer-loader.

It seems really similar to this fix: https://github.com/webpack/css-loader/pull/154

Example:
webpack:///./src/containers/App/src/src/containers/App/App.scss

This makes it hard to map all of the source files at once in Chrome's dev tools (for saving back to disk).

I'm using a webpack setup like the react-redux-universal-hot-example boilerplate, where I've also noted the problem:
https://github.com/erikras/react-redux-universal-hot-example/issues/572

Any ideas?

**Comment by d3viant0ne** [comment]
I regards to the change you referenced, you would end up with the same path before and after the change. 

If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this  one.
