### ISSUE TITLE
I am confused withI :local and :local()

### ISSUE THREAD

**Issue by a-lian123** [webpack/css-loader#195]
Sorry,my english is not so well.So I can't understand the explanation in the README.
I try this code to see what difference between :local and :local(),but the result looks the same:

```
:local .aa .bb{ color: green; }
:local (.aa) .bb{ color: green; }
:global(.xxx) :local(.aa) { background: red; }
:global .xxx :local .aa { background: red; }
```

result:

```
._3HCoCPfnT3zhuN2JF9v4uq ._27q3bxp4RYdMuT0j6zWyR7{ color: green; }
._3HCoCPfnT3zhuN2JF9v4uq ._27q3bxp4RYdMuT0j6zWyR7{ color: green; }
.xxx ._3HCoCPfnT3zhuN2JF9v4uq { background: red; }
.xxx ._3HCoCPfnT3zhuN2JF9v4uq { background: red; }
```

 What is the situation use :local() and What is the situation use  :local ? thanks!

**Comment by catalsdevelop** [comment]
hi,a-lian123.
The default selectors are all locals ,so .aa and :local(.aa) are the same result.
Any identifier with brackets will transform all selectors in to the corresponding scope,so :global(.foo .bar) means :global(.foo) :global(.bar) and :global(.foo) .bar means :global(.foo) :local(.bar).
A local scope selector will be transformed to a unique selector which defualt value is [hash:base64]. according to your setting.
