### ISSUE TITLE
Import external module into scss file

### ISSUE THREAD

**Issue by manuelmazzuola** [webpack/css-loader#196]
Is possible to import javascript variables into scss files ?

```
import red50 from 'material-ui/lib/styles/colors.js';

.title {
  color: red50;
}
```

colors.js is something like

```
module.exports = {                                                                                                                               

  red50: '#ffebee',                                                                                                                              
  red100: '#ffcdd2', 
```

**Comment by d3viant0ne** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support though you may also inquire in [Webpack Gitter](https://gitter.im/webpack/webpack). The issue tracker is for bug reports and feature discussions. See also our CONTRIBUTING guidelines.
