### ISSUE TITLE
variables in webpack's css loader

### ISSUE THREAD

**Issue by AvraamMavridis** [webpack/css-loader#197]
I started using the webpack's css loader and I find it really useful in terms of having "local scope" in css. What I need is variables e.g. I have something like this

```
:local(#names > input){
  flex: 0 1 100%;
  background: #2E2E2E;
  margin: 2px;
  border: 1px solid #FF5251;
}
```
I want to define a variable for the color, e.g. $pink = '#FF5251 Is there a way to do that inside this css file with the css loader or the only solution is to change loader and use sass ?

I mean, since it is not a "real" css file and it already has things like local and composes, someone would expect support for variables.

**Comment by dspnorman** [comment]
Have a look at @value, which is now part of webpack css-loader:
https://github.com/css-modules/postcss-modules-values

Using @value to pass arbitrary values between module files is similar to $sass-variables, but without the global scope implications.

**Comment by AvraamMavridis** [comment]
@dspnorman cool, thx! I will close the issue.
