### ISSUE TITLE
Address react-css-loader complaints?

### ISSUE THREAD

**Issue by kevinSuttle** [webpack/css-loader#201]
Apologies if this has been documented elsewhere. 
https://github.com/gajus/react-css-modules#whats-the-problem

cc: @markdalgleish @geelen

**Comment by vramana** [comment]
@kevinSuttle I think react-css-modules doesn't solve the problems in cleanest possible way.

> You have to use camelCase CSS class names.

This is not true. This resolves `css?modules&camelCase=dashes'` that problem 

> You have to use styles object whenever constructing a className.
> Mixing CSS Modules and global CSS classes is cumbersome.

Writing like this `export default CSSModules(Table, styles)` doesn't help either. They do ton of children cloning to achieve this which feels very bad to me. I think the best solution is write a babel plugin and apply transforms at compile times. Probably it won't solve all cases (when classes are  computed dynamically and stuff). But I think we can heuristically solve majority of common cases. 

> Reference to an undefined CSS Module resolves to undefined without a warning.

Again heuristic compile time analysis can be done here also probably. But will be little more work.

**Comment by d3viant0ne** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support though you may also inquire in [Webpack Gitter](https://gitter.im/webpack/webpack). The issue tracker is for bug reports and feature discussions. See also our CONTRIBUTING guidelines.
