### ISSUE TITLE
Composes in multiple files causes maligned imports

### ISSUE THREAD

**Issue by studiosciences** [webpack/css-loader#205]
Scenario:
* Backbone view imports buttonGroup.css, and buttonBar.css.
* buttonGroup.css has classes that compose button.css classes.
* buttonBar.css has classes that compose buttonGroup.css classes and button.css classes.  This makes button.css import a second time. It's inserted after buttonGroup.css which breaks some of the styles.

CSS writes out in the following order:
* button.css
* buttonGroup.css
* button.css <- shouldn't load again.
* buttonBar.css

I've spent a couple of days debugging this. It wasn't clear to me whether the postcss-modules-extract-imports was suppose to be handling this, it was an issue cause by processCss.js or it was some sort of limitation.

Thanks you! I hate to file an issue for something I don't fully understand.

**Comment by studiosciences** [comment]
This was a conflict with another custom plugin we had.

**Comment by terencechow** [comment]
@studiosciences do you remember what was causing this? I seem to have a similar issue

**Comment by studiosciences** [comment]
@terencechow It's taken me a couple of days to recall this much info and I'm not in the office to ask the guy that wrote the custom plugin. He had messed with the IDs (identifiers?) for the files in a web pack plugin to address some legacy issue. So basically webpack thought these were two different files. We just filtered out the CSS files and we were ok.
