### ISSUE TITLE
@import css as global to prevent hash class name generation

### ISSUE THREAD

**Issue by tsm91** [webpack/css-loader#213]
If i import bootstrap from node_modules it implicitly gets random class names. How can i prevent this?

`@import "bootstrap/dist/css/bootstrap.css";`

```
body .navbar___1eyp7 {
  position: relative;
  padding: .5rem 1rem;
}
```

```
loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[local]___[hash:base64:5]!postcss'

....

postcss: (bundler) => {
  return [
    require('stylelint')(),
    require('postcss-import')({ addDependencyTo: bundler }),
    require('precss')(),
    require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }),
    require('postcss-reporter')({ clearMessages: true })
  ];
}
```

**Comment by markdalgleish** [comment]
Bootstrap uses global classes, so you're naturally going to find integration with CSS Modules somewhat awkward. You might want to use separate loaders for CSS Modules and legacy global CSS like Bootstrap, i.e. name all of your scoped CSS like this: `SomeComponent.local.css`.

**Comment by tsm91** [comment]
@markdalgleish ahaa, thanks for the tip! 

Yeah a bit it is. I want to start my next project with postcss and css modules and also i recently switched to webpack (still working on it tho) so yeah, a lot of strange stuff annoys me, but this one got solved.
