### ISSUE TITLE
disabling css modules on a per-stylesheet basis

### ISSUE THREAD

**Issue by jonathanong** [webpack/css-loader#215]
assuming you have css modules enabled in your config, how do you disable css modules for specific css files? specifically, i want to disable it for dependencies, otherwise none of its styling will work.

anyone solve this?

**Comment by markdalgleish** [comment]
You can configure different loaders for different files, even though they're the same file type. Use CSS Modules for your locally scoped files, use global CSS for all your legacy files. A simple way you can achieve this is by naming all of your CSS Modules files like this: `MyComponent.local.css`, and then matching that pattern in your webpack config.

**Comment by developit** [comment]
@markdalgleish FYI - This seems to result in duplicated CSS.

**Comment by cgatian** [comment]
Would be nice to specify somehow through the import statement. Maybe Im missing something
