### ISSUE TITLE
Local class names without :local(...) prefix

### ISSUE THREAD

**Issue by Un3qual** [webpack/css-loader#219]
Would it be possible to add a setting to have local class names with out needing to have `:local(..,)` around everything? I have written a lot of CSS and would like to being using the local class names, but I don't have the time to manually add `:local()` to everything. Also, how do I use a local class names for multiple classes I.E `:local(.class1,.class2)` It compiles as a nested class. Thanks!

**Comment by markdalgleish** [comment]
This is what CSS Modules already does, just enable modules mode like so: `css-loader?modules`.
