### ISSUE TITLE
Better explaining :global vs :global() and :local vs :local()

### ISSUE THREAD

**Issue by mmahalwy** [webpack/css-loader#221]
Forgive my ignorance, but the explanation in the Readme is not very clear. I see that it outputs both as the same. What's the difference? 

Lastly, any suggestions when querying for a node? All I have is `querySelector('[class^="background"]')`

**Comment by d3viant0ne** [comment]
https://github.com/webpack/css-loader/issues/195#issuecomment-162386690

**Comment by mmahalwy** [comment]
thanks!
