### ISSUE TITLE
autoprefixer-loader has been deprecated in favor of postcss-loader

### ISSUE THREAD

**Issue by bebraw** [webpack/css-loader#227]
[autoprefixer-loader](https://www.npmjs.com/package/autoprefixer-loader) has become deprecated. It would be a good idea to point at [postcss-loader](https://www.npmjs.com/package/postcss-loader) instead in the readme.

**Comment by airtonix** [comment]
Actually it would be a good idea to just remove css-nano (which loads autoprefixer).

if you want postprocessing, pipe `cass-loader` into `postcss-loader`
