### ISSUE TITLE
Overwrite publicPath

### ISSUE THREAD

**Issue by gajus** [webpack/css-loader#234]
Is there a way to overwrite publicPath that CSS loader is using?

**Comment by gajus** [comment]
All our CSS assets are in a flat structure. Therefore all relative URLs are simply `./[asset name]`. However, we serve static assets from `./static` path relative to the current URL, therefore our `output.publicPath` is `./static/`.

**Comment by gajus** [comment]
Ah, it is the https://github.com/webpack/extract-text-webpack-plugin that uses the `output.publicPath` to resolve URLs.

**Comment by aflext** [comment]
@gajus Would you like to post your code ? I seemed to encounter the same question.

**Comment by gajus** [comment]
Sorry, it has been too long. Though as the former comment states, the solution is in the ExtractText config, not css-loader.

**Comment by aflext** [comment]
@gajus Thanks a lot anyway!
