### ISSUE TITLE
Can't disable colormin

### ISSUE THREAD

**Issue by ulnda** [webpack/css-loader#241]
Hello! I want to disable colormin in my loader:

`{
    test: /\.sass$/,
    loaders: ["style", "css?-colormin", "resolve-url", "sass?sourceMap&indentedSyntax"]
  }`

but it doesn't work. Because I've got in the original file the following code:

```
.some-style
  -webkit-tap-highlight-color: rgba(0,0,0,0)
```

In the output file I've got:

```
.some-style
  -webkit-tap-highlight-color: transparent
```

How can I disable colormin? Thanks in advance!

**Comment by SpaceK33z** [comment]
Do you still have this issue?

**Comment by ben-eb** [comment]
@SpaceK33z I already pushed a fix for this, the issue can be closed. 😄

https://github.com/ben-eb/postcss-colormin/issues/1
