### ISSUE TITLE
List of all possible [placeholders]?

### ISSUE THREAD

**Issue by wzup** [webpack/css-loader#246]
Could you pls provide a list of all possible placeholders? Now we know these. Are there any more?
```
[name]
[local]
[path]
[hash:base64:5]
```

**Comment by developit** [comment]
These are also supported:

```
[folder]   (parent dir name)
[ext]  (file extension)
[emoji:XXXX]  (emoji by codepoint)
```

From here: https://github.com/webpack/loader-utils/blob/master/index.js#L234

**Comment by psimyn** [comment]
duplicate of https://github.com/webpack/css-loader/issues/226 ?

**Comment by bebraw** [comment]
Closing as a duplicate.

**Comment by seggev319** [comment]
@developit link's broken..

**Comment by jdatskuid** [comment]
Updated link: https://github.com/webpack/loader-utils/#interpolatename
