### ISSUE TITLE
Any reasonable best practice how to write multiple classes that are from different source files?

### ISSUE THREAD

**Issue by wzup** [webpack/css-loader#247]
How to avoid such a syntax?

```
<section className={styles.fooSections + ' ' + styles.greenSection}>
```

I want to have clear and nice:
```
<section className="fooSections greenSection">
```
`fooSections` is from other file, global
`greenSection` is local

With that I don't want one `className={style.className}` that combines both. Just because it is not right. You cannot tell right off the bat how many class names are there:
```
<section className={styles.mySectionClass}> // this works but it is not right

.mySectionClass {
    composes: fooSections from "./../../../../../sections.scss"
}

// which generates something like:
mySectionClass: "fooSections_jhcdh75 greenSection_mcfjfr85"
```

**Comment by psimyn** [comment]
Perhaps one of these?

```
<section className={`${styles.fooSections} ${styles.greenSection}`}>

<section className={`${styles.fooSections} greenSection`}>
```

second one depends on 'greenSection' is the actual global class name

**Comment by bebraw** [comment]
@psimyn's suggestion looks good. Closing.
