### ISSUE TITLE
 Minification of CSS in -p mode removes -moz/-o/-ms rules

### ISSUE THREAD

**Issue by robinsving** [webpack/css-loader#248]
Copied from [webpack issue#2158](https://github.com/webpack/webpack/issues/2158)

---

I was testing out Webpack with the `-p` flag and got some weird results in my CSS compared to my regular page. One of these errors was the aparent removal of CSS code.

CSS in my .css-file:
```
.systembar::before {
  background: #0066b3;
  background: -o-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -moz-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -webkit-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -ms-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0.1, #a2c517), color-stop(0.3, #009046), color-stop(0.5, #0082b6), color-stop(0.75, #151f77), color-stop(1, #db0050));
  background: linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
}
```

After inspecting the ::before object in Firefox:

```
{
    background: #0066b3;
    background: -webkit-linear-gradient(left,#a2c517 10%,#009046 30%,#0082b6 50%,#151f77 75%,#db0050);
    background: -webkit-gradient(linear,left top,right top,color-stop(.1,#a2c517),color-stop(.3,#009046),color-stop(.5,#0082b6),color-stop(.75,#151f77),color-stop(1,#db0050));
    background: linear-gradient(left,#a2c517 10%,#009046 30%,#0082b6 50%,#151f77 75%,#db0050);
}
```
This is of course not matched to Firefox, and the background becomes blue instead of gradient

It seems that the minification done by `-p` removed the Firefox/Opera/IE-specific lines, and kept only the Wekbit parts.
Why is this done, and how can I prevent this bug?

---

I just wanted to move this to the right repo. I think that the anwser has been given in the form of adding `-autoprefixer` to add support for older browsers. Though why the latest Firefox couldn't handle the normal rule despite support claimed by caniuse.com I don't know.

**Comment by danpantry** [comment]
See the README of this module.

> By default the css-loader minimizes the css if specified by the module system.

In some cases the minification is destructive to the css, so you can provide some options to it. cssnano is used for minification and you find a list of options here. Just provide them as query parameter: i. e. require("css-loader?-autoprefixer") to disable removing of deprecated vendor prefixes.

You can also disable or enforce minification with the minimize query parameter.

require("css-loader?minimize!./file.css") (enforced)

require("css-loader?-minimize!./file.css") (disabled)

**Comment by psimyn** [comment]
@robinsving you are missing the `to` keyword in the direction

 background: linear-gradient(**to** left,#a2c517 10%,#009046 30%,#0082b6 50%,#151f77 75%,#db0050);

**Comment by robinsving** [comment]
Holy crap @psimyn, that was the reason that FF didn't pick up the line. Thanks!
