### ISSUE TITLE
Modules. Different hash on server and client 

### ISSUE THREAD

**Issue by smirnovshina** [webpack/css-loader#267]
Trying to use css modules with SSR. My css loader configs:
```js
// client
      test: /\.css$/,
      loader: ExtractTextPlugin.extract(
        'style',
        'css?modules&localIdentName=[hash]&camelCase&importLoaders=1!postcss'
      )
```
```js
// server
      test: /\.css$/,
      loader: 'css/locals?modules&localIdentName=[hash]&camelCase'
```
It generates different hashes for server and client. Hence React throw an error:
![1](https://cloud.githubusercontent.com/assets/6762673/14768721/3f20903a-0a52-11e6-9dc2-d43f90853640.png)

How a hash generate, based on what? What could I be doing wrong?

**UPD**
This problem is somehow connected to entry point in webpack server bundle config:

```js
// with this working well
  context: path.join(__dirname, 'server'),
  entry: {
    server: './index.js'
  },

// with this generating wrong hashes
  context: __dirname,
  entry: {
    server: './server/index.js'
  },
```

**Comment by alexanderchr** [comment]
The path of the resource relative to `context` is used to create the hash, so this is expected behaviour. If But, if I'm following the code correctly you can pass a `context` in the loader query, i.e.:

```js
'css?context=../server'
```

**Comment by arvigeus** [comment]
If someone is dummy like me and unable to solve it, just pass { context: <src-dir> } to css-loader options for both client and server. (Note: this might break something, but works for me)

**Comment by evilebottnawi** [comment]
@osenvosem @arvigeus Can your do PR in docs about this?

**Comment by adamrights** [comment]
Had a similar issue. Using webpack4. Found this fixed context in our case:  

![image](https://user-images.githubusercontent.com/986771/50852969-09d7ea00-134f-11e9-8cb5-8fbb557478e9.png)
