### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by willin** [webpack/css-loader#270]
```js
	isOldIE = memoize(function() {
			return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
		}),
```

**Comment by bebraw** [comment]
Where is that coming from? I don't see that in css-loader.

**Comment by psimyn** [comment]
looks like it comes from style-loader https://github.com/webpack/style-loader/blob/master/addStyles.js#L13

Dupe of this I suspect https://github.com/webpack/style-loader/issues/109

@willin is style-loader output being used for server-side code?

**Comment by bebraw** [comment]
@psimyn Good catch! I'll close this in favor of that then.
