### ISSUE TITLE
css-loader fails to parse npm linked modules correctly

### ISSUE THREAD

**Issue by dptoot** [webpack/css-loader#300]
Referencing a CSS file from a node_module package within my webpack config works fine 

```javascript
const CSS_PATHS = [
  config.paths.demo,
  path.join(ROOT_PATH, 'style.css'),
  path.join(ROOT_PATH, 'node_modules', 'chopstrap', 'dist', 'chopstrap.css'),
];
...

module: {
      loaders: [
        {
          test: /\.css$/,
          loaders: ['style', 'css'],
          include: CSS_PATHS
        },
...

```

but if I link to a local package with npm link I receive the error
```
ERROR in ../chopstrap/dist/chopstrap.css
Module parse failed: C:\Users\jelewis1\Desktop\work\chopstrap\dist\chopstrap.css Unexpected character '@' (1:0)
```

It seems that the loader isn't interpreting valid CSS correctly when referenced through a symlink.

**Comment by alferov** [comment]
Are you using postcss-loader?

**Comment by dptoot** [comment]
Of course as usual it was me.  Choking on sass that I wasn't processing correctly with extractTextPlugin.  Sorry for the wasted time.
