### ISSUE TITLE
Only local scope first class

### ISSUE THREAD

**Issue by psypersky** [webpack/css-loader#304]
Hi, i want to take the local scoped class and use it in my components, but i don't want to have to import every name from the file

```    
<header className={styles.wrapper}>
      <div className="inner">
        <div className="logo">
```

and the way it works now i would have to do 

```
    <header className={styles.wrapper}>
      <div className={styles.inner}>
        <div className={styles.logo}>
```

which makes it more difficult to read, is it possible to only format the wrapper class?

Thanks :)

**Comment by zorahrel** [comment]
You can obviously assign only the first wrapper class and using a css pre-processor (like [SASS](https://github.com/jtangelder/sass-loader)) nest inner and logo like so:
`.wrapper {
    color: blue;
    .inner {
        color: red;
        .logo {
            color: yellow;
        }
    }
`

**Comment by sokra** [comment]
You can do that with `:local(...)`, but I would not recommend it.
