### ISSUE TITLE
when I use node strict mode, I get an error : ERROR in addresses is not defined

### ISSUE THREAD

**Issue by tangdaohai** [webpack/css-loader#330]
error : 

    ERROR in addresses is not defined
    @ ./client/index.css 4:14-76 13:2-17:4 14:20-82

**Comment by tangdaohai** [comment]
my Node parameters : 
 
    ["--es_staging", "--harmony", "--use-strict"]

**Comment by poacher2k** [comment]
Hi!
I experienced the exact same issue, and found out that I had not added some fonts to my project folder that my css was referencing. Hope this helps you.

**Comment by tangdaohai** [comment]
thanks

**Comment by SpaceK33z** [comment]
@tangdaohai, did this resolve your issue? Please close this ticket if so.
