### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by sapegin** [webpack/css-loader#336]
Because [it’s important](https://medium.com/@sapegin/add-the-fucking-change-log-3d82d758d8b0).

**Comment by runechronos** [comment]
Hell yeah it is :s,

I can't manage to find a proper version combination between css-loader, postcss-loader and autoprefixer... Trying to update a project with newer dependencies. If u have any idea, i'm here
Trying to use autoprefixer@6.4.1, postcss-loader@0.13.0 and css-loader@0.25 but, i get a blank page something is going wrong but i only get some "deprecated warning" lines

**Comment by TheLarkInn** [comment]
@sapegin would love some extra support to add one, but some changes from core can inadvertently affect the loader. If that is what the humoresqe issue is in response to, then know that we are actively working to get this functionality first to webpack/webpack, and then hopefully with the support of more people can have the same for our loaders and plugins. 

Thank you for caring about the future of the project and repo's around it.

**Comment by sapegin** [comment]
Thank you very much @TheLarkInn, I appreciate very much what you do for Webpack. I know it’s hard ;-} Let me know if I can help.

**Comment by SpaceK33z** [comment]
For `0.26.0` there is a changelog now (GitHub releases). We'll try to think of this with the next releases.
