### ISSUE TITLE
Option for making all class as local classes

### ISSUE THREAD

**Issue by pa-nam** [webpack/css-loader#349]
I dont want to type `:local` all the times, so I wonder if we can have an option for making all classes as local classes. We can have include option to apply for only some specific folders.

**Comment by CookPete** [comment]
Is the [`modules` parameter](https://github.com/webpack/css-loader#css-modules) what you are after? It outputs local classes by default.

**Comment by pa-nam** [comment]
Thanks, I got it. It has been a long time since I used it and I didn't read the docs carefully again. My bad, closing.
