### ISSUE TITLE
Ignore images for loading

### ISSUE THREAD

**Issue by grydstedt** [webpack/css-loader#35]
Is there a way I can tell the loader not to resolve a url to images in a url()

Would like:
background-image: url('../img/some-image.gif');
to output the same thing:
background-image: url('../img/some-image.gif');

**Comment by sokra** [comment]
no, but you can use the `raw-loader` instead of the `css-loader`.

**Comment by grydstedt** [comment]
Thanks

**Comment by unlocomqx** [comment]
This worked for me `css-loader?url=false`
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/156#issuecomment-402265124
