### ISSUE TITLE
Disable remove properties default by autoprefixer?

### ISSUE THREAD

**Issue by acrazing** [webpack/css-loader#369]
Because we always use `autoprefixer` to add prefixes for old browsers with custom `browsers` config, just like `iOS >= 8` etc. But `cssnano` use default `browsers` config for `autoprefixer` to remove properties if we don't pass config to it. And then we need to write the config twice!

For example:

```js
// webpack.config.js
var autoprefixerrc = {
  browsers: ['iOS >= 8']
}

module.exports = {
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: 'css-loader?' + JSON.stringify({autoprefixer: autoprefixer}) + '!postcss-loader'
      }
    ]
  },
  postcss: [
    autoprefixer(autoprefixerrc)
  ]
}
```

**Comment by Asgator** [comment]
https://github.com/webpack/css-loader/commit/008e6fd8c2f4621269410de194e9117791c09d15

**Comment by acrazing** [comment]
OMG!

How long do we need to wait for the next version? I don't know how many people gave up the flex layout for this reason. 😂😂

**Comment by SpaceK33z** [comment]
We will certainly release a new version when webpack v2 comes out (shouldn't be too long), since #320 needs to be fixed for v2. However, I'll ask if we can release a version before this.

**Comment by acrazing** [comment]
I think its necessary if change too much between webpack 1 and 2.

**Comment by stephanedemotte** [comment]
+1 for a new release asap :)

**Comment by SpaceK33z** [comment]
Done! See `0.26.0`.
