### ISSUE TITLE
error when using Css Modules `composes` with webpack 2

### ISSUE THREAD

**Issue by JounQin** [webpack/css-loader#382]
I've looked through the issue https://github.com/webpack/css-loader/issues/131, but it didn't work.

---

I'm using CssModules with `css-loader`, `postcss-loader`, `stylus-loader`, it throws an error:

> Uncaught (in promise) TypeError: Cannot read property 'modal' of undefined

I've tried to change the `importLoaders` to be "2", but this error still occurs.

My total loader config string is:

> style-loader!css-loader?-minimize&modules&camelCase&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]&sourceMap!postcss-loader?sourceMap!stylus-loader?sourceMap

I looked through the compiled style code:
``` js
exports.locals = {
	"prompt": "prompt-modal__prompt___ySAyV " + __webpack_require__(699).locals["modal"] + "",
	"prompt": "prompt-modal__prompt___ySAyV " + __webpack_require__(699).locals["modal"] + "",
	"btn-prompt": "prompt-modal__btn-prompt___2k-dR",
	"btnPrompt": "prompt-modal__btn-prompt___2k-dR",
	"prompt-text": "prompt-modal__prompt-text___gQ1v5",
	"promptText": "prompt-modal__prompt-text___gQ1v5"
};
```

*__webpack_require__(699)* is an array as following:
![](http://ww1.sinaimg.cn/large/006tNc79gw1fac807ylwoj31e40hsq6o.jpg)

**Comment by amsayk** [comment]
I'm also getting this error but with sass-loader and using webpack 1.

**Comment by JounQin** [comment]
I'm using `css-loader` in a `Vue` project, it seems to be an issue of `vue-loader`.

https://github.com/vuejs/vue-loader/issues/501

I fix this problem by importing `.styl` file in *script* by myself, so that it won't be imported through `vue-loader`.
