### ISSUE TITLE
components are not using bootstrap.css after integrating it

### ISSUE THREAD

**Issue by harishrohokale** [webpack/css-loader#394]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by SpaceK33z** [comment]
closing for obvious reasons...
