### ISSUE TITLE
npm install css-loader --save-dev  

### ISSUE THREAD

**Issue by chkbuy** [webpack/css-loader#395]
E:\mynode\chkbuy\chk-admin>npm -v
4.0.5

E:\mynode\chkbuy\chk-admin>node -v
v5.9.0

E:\mynode\chkbuy\chk-admin>npm install css-loader --save-dev
npm ERR! cb() never called!

**Comment by SpaceK33z** [comment]
This is an issue with npm. Also, make sure  you use node v6, node v5 is no longer main AFAIK.

**Comment by nsklkn** [comment]
updating to npm 4.1.1 and node 6.9.2 fixes this problem
