### ISSUE TITLE
webpack2 css-loader css-modules

### ISSUE THREAD

**Issue by fengyun2** [webpack/css-loader#396]
## versions:

"webpack": "^2.1.0-beta.27",
"css-loader": "^0.26.1"

## problem:

I want to custom css-modules localIdentName:  `localIdentName=[path]___[name]__[local]___[hash:base64:5]`

demo:

```js
{
                test: /\.(scss|sass)$/,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: [
                    {
                        loader: 'css-loader',
                        query: {
                            modules: true,
                            importLoaders: 1,
                            localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
                        }
                    },
                    'postcss-loader',
                    'sass-loader']
                })
            },
```
But the `localIdentName=[path]___[name]__[local]___[hash:base64:5]` of the `[path]` can't analyze. However, in `webpack1.3` can be analyzed out.

## result

![image](https://cloud.githubusercontent.com/assets/8147202/21546524/3d71828a-ce1a-11e6-8f40-f0477f5905bc.png)

**Comment by SickSAMA** [comment]
If you're using LoaderOptionsPlugin, specify context.
```javascript
new webpack.LoaderOptionsPlugin({
  options: {
    context: __dirname,
    postcss: ...
  }
})
```

**Comment by wZi** [comment]
it work for me. Thank U very much.

**Comment by tvrcgo** [comment]
Works for me ! thanks.

**Comment by tonokim** [comment]
Is work for me !3Q
