### ISSUE TITLE
Semicolon ( ; ) in comments throws errors

### ISSUE THREAD

**Issue by wzup** [webpack/css-loader#397]
Semicolon after `"bootstrap"` throws an error

>ERROR in ./styles/foo.css
> Module build failed: CssSyntaxError: C:\css-loader!C:\app\assets\styles\foo.css:1:1: Unknown word

```
// @import "bootstrap";  <- semicolon is error

.key {
    color: #222
}
```

**Comment by billyjanitsch** [comment]
The parse error is correct: `// inline comments` don't exist in CSS -- only `/* block comments */` do.
