### ISSUE TITLE
loading fonts via url() only works in production mode

### ISSUE THREAD

**Issue by Turbo87** [webpack/css-loader#41]
I observed some weird behavior when I was trying to use [font-awesome](http://fortawesome.github.io/Font-Awesome/) in a webpack powered project.

I trimmed the code down as much as possible and put it into a gist: https://gist.github.com/Turbo87/e8e941e68308d3b40ef6

I installed `font-awesome` via `npm` and use `require` to import its CSS file through the `style` and `css` loaders. The CSS file has a `@font-face` which uses `url()` with a relative path to point to the font file(s). When I compile this with webpack in production mode everything works just as expected, but once I drop the `-p` parameter the code suddenly tries to load the font file from `/` for whatever reason and fails.

I observed that behavior with Google Chrome *and* Firefox, so it is probably not a browser issue.

**Comment by jhnns** [comment]
Seems to be caused by the `sourceMap` option somehow

**Comment by Turbo87** [comment]
@sokra @jhnns any ideas how to resolve this?

**Comment by sokra** [comment]
Switch off sourceMaps for CSS...

**Comment by sokra** [comment]
see #29

**Comment by Turbo87** [comment]
well I consider switching sourceMaps off a workaround, but since this is a duplicate of #29 I'll close this issue. feel free to use the gist linked above as a way to reproduce the problem.

**Comment by sokra** [comment]
yes. I would like to fix it, but the problem is that I have no idea how to do that. SourceMaps doesn't seem to work in `<style>` tags and a current approach give permission errors on external resources.

**Comment by Semigradsky** [comment]
The same issue. I hope a solution will be found.
