### ISSUE TITLE
Root relative outputs relative URL in single page application

### ISSUE THREAD

**Issue by fourlastor** [webpack/css-loader#42]
Hello, I noticed the root-relative option https://github.com/webpack/css-loader#root-relative-urls doesn't work well if you have a single page application that uses `history.pushState`.

Example:

I have the following structure:
```
/
--/src
  --/assets/images/hello.png
  --/css/style.css
--/build
  -- (here is where files go after compilation)
```

And I have an `hello.css` file with the following content:

```css
#hello {
  background-image: url("/assets/images/hello.png")
}
```

Now, my config for CSS and PNG files will be something like:

```
{test: /\.css$/, loader: 'style-loader!css-loader?root=..}
{test: /\.(png)$/, loader: 'file-loader?name=[path][name].[ext]?[hash]&context=./src'}
```

This results in the output-ed css being (notice the missing `/` before the path):

```css
#hello {
  background-image: url("assets/images/hello.png")
}
```

Which will work well as long as I access my application at `/`, but will fail for example if I share an URL like `/hello/world` because then the background image will be searched at `/hello/world/assets/images/hello.png`.

Should absoulte paths be translated? If I don't specify a root, then the file-loader doesn't kick in so I won't have my assets during build.

I see 2 options:

- When you don't specify a root, css-loader requires the files anyway, just doesn't change the url.
- If you specify a root, the loader is used but the path isn't translated.

What do you think?

**Comment by sokra** [comment]
I also see 2 options:

* provide a `output.publicPath`. i. e. `"/"`. It's prefixed all generated urls.
* use a `<base>` tag in your HTML to set to correct base path.

**Comment by fourlastor** [comment]
That's great! Thank you a lot :)
