### ISSUE TITLE
css loader chokes on valid CSS

### ISSUE THREAD

**Issue by haf** [webpack/css-loader#43]
https://gist.github.com/haf/a632962b86409b8c51e3

```
ERROR in ./~/css-loader?root=..!./css/front.css
Module build failed: Error: Please check the validity of the CSS block starting from the line #414
    at throwError (/node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at getBlock (/node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:755:18)
```

As you can see, there's no line 414.

**Comment by sokra** [comment]
yeah. We propably need to implement our own parser, which just grabs `url(...)` and `@import ...`.

**Comment by haf** [comment]
Ok...? That would need to allow all chars in [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.1), and the [CSS2 spec 4.3.4](http://www.w3.org/TR/CSS2/syndata.html#uri). So that's implemented by these regexes:

``` javascript
var uriSingleQ = /url\('?(?<path>([a-zA-Z\.\/\-_0-9:~?\[\]@!$&\(\)*+,;="]|\\')*)'?\)/,
    uriDoubleQ = /url\("?(?<path>([a-zA-Z\.\/\-_0-9:~?\[\]@!$&\(\)*+,;=']|\\")*)"?\)/

var importUriSingleQ = /@import (url\()?'?(?<path>([a-zA-Z\.\/\-_0-9:~?\[\]@!$&\(\)*+,;="]|\\')*)'?\)?/,
    importUriDoubleQ = /@import (url\()?"?(?<path>([a-zA-Z\.\/\-_0-9:~?\[\]@!$&\(\)*+,;=']|\\")*)"?\)?/
```

since JS doesn't have recursion in their regexps.

This works with my sample file.

Can you throw such a loader together now, please, so I can publish my site? I would really owe you one.

**Comment by mtscout6** [comment]
Do you all have thoughts on using this [css](https://www.npmjs.com/package/css) parser? It only breaks out the code to an AST which you could then query for url from ast trees that are of type import.

```
$ node
> var css = require('css');
undefined
> var ast = css.parse('@import url("some.css");');
undefined
> console.log(ast);
{ type: 'stylesheet',
  stylesheet: { rules: [ [Object] ], parsingErrors: [] } }
undefined
> console.log(ast.stylesheet.rules[0]);
{ type: 'import',
  import: 'url("some.css")',
  position:
   { start: { line: 1, column: 1 },
     end: { line: 1, column: 25 },
     source: undefined } }
undefined
> console.log(ast.stylesheet.rules[0].import);
url("some.css")
```

**Comment by haf** [comment]
Seems like that parser has a bug in the parsing of URLs with `)`, that I mentioned in my regex: https://github.com/reworkcss/css/issues/67#issuecomment-83348372

**Comment by sokra** [comment]
> Ok...? That would need to allow all chars in RFC3986, and the CSS2 spec 4.3.4 and import like these. So that's implemented by these regexes:

I would like to make it simpler and just allow everything except the end mark:

`/url\s*\(\s*"([^"]*)\s*\)/` etc.
We also need to check for comments and ignore them.

Here is a simple module which combines statemachine with regex for parsing. i. e. the html-loader uses it to parse the html: https://github.com/webpack/fastparse

cc @jhnns

**Comment by mgmorcos** [comment]
:+1:

**Comment by chrisguerrero** [comment]
Any word on this?

**Comment by haf** [comment]
For me this has meant I can't use webpack right now. I did some looking into how to write a regex parser, but there's just so much undocumented structure that I don't recognise, so I gave up. I haven't had any other contact with anyone from webpack.

**Comment by chrisguerrero** [comment]
@haf I just got around this by switching the filename to .scss and using the sass-loader

**Comment by haf** [comment]
Ok, I had problems with that loader as well; other problems, like race-conditions breaking 25 minute builds (latest) and problems finding a stable version in general, unfortunately.

**Comment by jhnns** [comment]
Thx @sokra. I'm totally busy right now and haven't found the time to investigate this :disappointed:
