### ISSUE TITLE
Can't figure out how to enable `disableStructuralMinification` via loaders

### ISSUE THREAD

**Issue by globexdesigns** [webpack/css-loader#46]
Uglify is breaking all sorts of things with my CSS so I'm trying to enable `disableStructuralMinification` but I can't tell if it's working as nothing is changing. I've tried:

```
{test: /\.css$/, loader: 'style!css?disableStructuralMinification!'},
{test: /\.less$/, loaders: [
	"style-loader",
	"css-loader",
	"less-loader"
]}
```

And then I tried

```
{test: /\.css$/, loader: 'style!css},
{test: /\.less$/, loaders: [
	"style-loader",
	"css-loader?disableStructuralMinification!'",
	"less-loader"
]}
```

But it doesn't seem to resolve my issues. The minification process still moves CSS rules around in such a  way that causes broken styling in my app.

What am I doing wrong?

**Comment by sokra** [comment]
We switched from csso to clean-css, so this is no longer available.

Use this list of options instead:

https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically

i. e. `css-loader?-restructuring,keepBreaks`

**Comment by globexdesigns** [comment]
Thanks. That did the trick.

I'll keep this issue open so that you can remember to update the docs.
