### ISSUE TITLE
Using url(path) with resolve.alias

### ISSUE THREAD

**Issue by SimenB** [webpack/css-loader#49]
I have a few images in a shared location, which I import in a `css` file. This shared location has a lot of code shared between 5 webapps within the same project, and I have defined the alias `common-assets` in my config, which works great for every asset/module, except for css. The path is normalized by `css-loader` (I think?) to be relative, which breaks.

Is there any clean way to use the alias, or do I have to go `url("../../../../../../../../common/assets/images/image.png")` instead of the much cleaner `url("common-assets/images/image.png")`? If I do the latter, the actual import becomes `url("./common-assets/images/image.png")`, which is wrong, and fails the build.

**Comment by sokra** [comment]
https://github.com/webpack/css-loader#usage

`url("~common-assets/images/image.png")`

**Comment by SimenB** [comment]
Ah, of course, that makes sense.
I was thinking that it only resolved modules (i.e. from `node_modules`),
but that it resolves things _like_ modules makes much more sense.
Thanks!

**Comment by SimenB** [comment]
Ah, of course, that makes sense.
I was thinking that it only resolved modules (i.e. from `node_modules`),
but that it resolves things _like_ modules makes much more sense.
Thanks!

**Comment by cj** [comment]
@sokra I tried this but I'm getting an error http://prntscr.com/afub2r am I missing something?

**Comment by cj** [comment]
I actually think this is a postcss/postcss-import issue, I've created a ticket there.

**Comment by mrdulin** [comment]
@sokra `url("~common-assets/images/image.png")` worked. But what's the meaning of `~` symbol?

**Comment by SimenB** [comment]
It means that it's a module and not a relative path

**Comment by j-u-p-iter** [comment]
Guys, may be this stuff should be documented?

**Comment by j-u-p-iter** [comment]
Pretty cool! Is this documented somewhere?

**Comment by viT-1** [comment]
> Pretty cool! Is this documented somewhere?

https://webpack.js.org/loaders/css-loader/#import
