### ISSUE TITLE
Module require is case insenitive

### ISSUE THREAD

**Issue by SimenB** [webpack/css-loader#53]
Code that worked on my Mac failed when I used my Linux box, because of a failure (on my part) in casing.

Node.js `require` is case sensitive, would it be possible to copy that behavior? Not sure if it's this plugin er Webpack core.

Breaking change for something minor, but I think consistency is important.

```css
@import url("~dataTables/media/css/jquery.datatables.css");
```
vs.
```css

@import url("~datatables/media/css/jquery.dataTables.css");
```

First one failed, second is the correct one

**Comment by sokra** [comment]
It depends on the filesystem. There would be a performance cost if we test every request for correct casing...

**Comment by SimenB** [comment]
I don't know how you resolve modules, but can't you just use a case sensitive regex or something?
