### ISSUE TITLE
Use PostCSS

### ISSUE THREAD

**Issue by ai** [webpack/css-loader#54]
`fastparse` is awesome tool. But if you will move to PostCSS you will have these benefits:

1. Most of source map code will be in PostCSS.
2. You can replace `url()` and support `@import` with full CSS parsing. It is much safer. We are already have awesome plugins for `url()` and `@import`.
3. PostCSS has “[Safe Mode](https://github.com/postcss/postcss#safe-mode)” to parse any legacy CSS (even broken).
4. Right now @ben-eb creating awesome *modular* CSS minifier (it is much easier to fix and develop modular tool) [cssnano](https://github.com/ben-eb/cssnano). Right now it has [better results](http://goalsmashers.github.io/css-minification-benchmark/) that [clean-css] without advanced mode. So, when it became equal to clean-css, we can use it, because it is a PostCSS plugin with same source map support.

@markdalgleish what do you think as PostCSS plugin developer?

**Comment by markdalgleish** [comment]
@ai It worked really well for me given I had zero experience beforehand.

One question I have though—does PostCSS parse selectors into an AST? I'm currently transforming selectors using regular expressions which I know isn't going to work in the long run, and it'd be much better to operate on an AST instead of a string.

**Comment by ai** [comment]
@markdalgleish there is no selector parser right now and you can use [css-selector-parser](https://github.com/mdevils/node-css-selector-parser). @ben-eb is developing new parser, but as I know it will not be ready in this month.

**Comment by sokra** [comment]
PostCSS is nice. We previously used a full parser for the `url()` and `imports` (and now `local`) parsing, but using a simple string parser has the following benefits:

* Performance (we are just do RegExp matching)
* Compatible with future CSS extension of weird syntax used by some libs (This occured with the previous parser #43 #16 #36 #24, this may not be an issue currently, but could be in future when PostCSS get less maintained).
* We can easily add our own parsing stuff (like locals) and don't need to traverse the AST (which may change)
* We don't need a full AST
* It works and is simple

I'm fine with changing the css minimizer to PostCSS if it's better.

**Comment by ai** [comment]
@sokra but it is not safe ;).

```css
a {
    content: "do not use url(path)";
}
```

**Comment by ai** [comment]
@sokra and more details for you reasonable counterarguments:

* Of course, regexp shouldbe faster, than parser. But PostCSS is one of [the fastest parsers](https://github.com/postcss/postcss/blob/master/benchmark/parsers.js) written on JS. It is 4.5 times faster, that gonzales, that you use before.
* PostCSS Safe Mode is a answer for future compatible. It will parse anything.
* What is a locals? Is it relevant for [postcss-local-scope](https://github.com/markdalgleish/postcss-local-scope)?
* We need a AST to safe change CSS.
* It is not really simple right now. You have a lot of soure map code, which will be removed with PostCSS. PostCSS already had good [postcss-url](https://github.com/postcss/postcss-url) and [postcss-import](https://github.com/postcss/postcss-import) by @MoOx. You can use them and it will clean your code and be better for maintaining.

**Comment by sokra** [comment]
If you want to do a PR, feel free to do so, but I still think it not worth the work. The current parser is functional and works fine. postcss-url and postcss-import won't help here, because they do it different than the css-loader.

**Comment by MoOx** [comment]
> The current parser is functional and works fine

Not really, there is some case with latest css syntax is causing issue (if you minify) which break the process.

**Comment by sokra** [comment]
The minimizer and the parser are some separate things in the css-loader. I'm fine with replacing the minimizer with PostCSS (that not much work).

**Comment by airtonix** [comment]
css-loader shouldn't do any post processing...
