### ISSUE TITLE
woff2 failure

### ISSUE THREAD

**Issue by braco** [webpack/css-loader#55]
File seems to be valid, and:

```
ERROR in ./www/fonts/font.woff2?-p2dq1s
Module parse failed: [..]/fonts/font.woff2?-p2dq1s Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./www/css/index.css 2:34960-34998
```

All other font files are fine.

**Comment by sokra** [comment]
`/\.woff2$/` -> `/\.woff2($|\?)/`

**Comment by globexdesigns** [comment]
I've started having this issue recently as well with woff2 fonts not loading. However, for me I don't get any errors and it only occurs when I enable `UglifyJsPlugin({minimize: true})`

**Comment by mikepb** [comment]
Just wasted three hours to find that `css-loader` broke URL parsing... 0.12.1 parses and finds font urls just fine, but 0.13.0 doesn't. I suspect the issue is in `parseSource.js` because that's where the unhelpfully named `stuff.urls` array is populated.

**Comment by nmccready** [comment]
https://github.com/webpack/less-loader/issues/44

**Comment by matiaslarsson** [comment]
+1

**Comment by d3viant0ne** [comment]
If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this exceptionally old one.
