### ISSUE TITLE
0.13.0 breaks url parsing

### ISSUE THREAD

**Issue by mikepb** [webpack/css-loader#61]
See #55

**Comment by sokra** [comment]
Can you give a little more details?

**Comment by ALF-er** [comment]
Hello, I've found that new builds (after 0.13.0) ignores ~ in path. 
For example:
in my *.styl file I have `url("~fonts/proxima-nova/proxima_nova_semibold.woff")`
but browser trying to load `http://localhost:4000/~fonts/proxima-nova/proxima_nova_semibold.woff`

In previous versions it works fine =| Looks like related issue for this one

**Comment by mikepb** [comment]
Hmm... I'm not able to reproduce the issue this morning with 0.13.0 or 0.14.4.

**Comment by ALF-er** [comment]
Strange. It was stable issue for 3 days for me. But now it's gone =| I need some exorcist, I think =) Sorry to trouble
