### ISSUE TITLE
Unable to resolve `css-base.js` when using css-loader

### ISSUE THREAD

**Issue by maoueh** [webpack/css-loader#64]
When using the `css-loader` with a simple `require("css!custom.css");` and an empty `custom.css` file, I receive the following error:

```
ERROR in ./~/css-loader!./app/css/custom.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/css-loader/lib/css-base.js in C:\Gnu\tmp\css-loader-webpack/app/css
 @ ./~/css-loader!./app/css/custom.css 1:27-85
```

This seems to be a Windows specific error as I tried the same thing on a Unix system and it works there. So, probably a path problem when trying to resolve this line in `/lib/loader.js`:

```
163: return "exports = module.exports = require(" + loaderUtils.stringifyRequest(this, require.resolve("./css-base.js")) + ")();\n" +
```

I'm looking into guide lines on how to debug and hunt this bug. Any code location or ideas is welcomed.

To replicate, here a simple test case (on a Windows system).

```
# Layout
$ tree
├── app
│   ├── css
│   │   └── custom.css
│   └── js
│       └── main.js
└── webpack.config.js

# Node Modules
$ npm install style-loader css-loader

# app/css/custom.css

# app/js/main.js
require("css!custom.css");

# webpack.config.js
module.exports = {
  entry: "main.js",
  output: { filename: "bundle.js" },
  resolve: { root: [__dirname + "/app/css", __dirname + "/app/js"] },
};

# Command
$ webpack
Hash: 9eb81684d5adc83ab296
Version: webpack 1.9.10
Time: 216ms
    Asset    Size  Chunks             Chunk Names
bundle.js  1.8 kB       0  [emitted]  main
   [0] ./app/js/main.js 26 bytes {0} [built]
    + 1 hidden modules

ERROR in ./~/css-loader!./app/css/custom.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/css-loader/lib/css-base.js in C:\Gnu\tmp\css-loader-webpack/app/css
 @ ./~/css-loader!./app/css/custom.css 1:27-85
```

**Comment by maoueh** [comment]
Ok, it appears that the problem was simply how module root paths were defined for `resolve.root` configuration options.

Didn't think it was really needed but path really want to be normalized so separators are the one of the current filesystem. 

This is not working because paths becomes `c:\work\project\app/js` and `c:\work\project\app/css`:

```
module.exports = {
  entry: "main.js",
  output: { filename: "bundle.js" },
  resolve: { root: [__dirname + "/app/css", __dirname + "/app/js"] },
};
```

To fix the issue, simply use `path.join` which correctly normalize separators so paths use the correct separator for the filesystem (i.e. `c:\work\project\app\js` and `c:\work\project\app\css` on Windows):

```
var path = require('path');

module.exports = {
  entry: "main.js",
  output: { filename: "bundle.js" },
  resolve: { root: [path.join(__dirname, "app/css"), path.join(__dirname, "app/js")] },
};
```

This problem also bit me with `watch: true` config. It's after resolving this one that I thought it could be the same problem here and it was.

Bottom point, I would like to add this information somewhere on the website. Is it open source, I would contribute a PR.

Regards,
Matt

**Comment by L3V147H4N** [comment]
does not work for me :p

**Comment by JerJohn15** [comment]
I am also having this problem. I'm currently running the latest version: 0.23.1
