### ISSUE TITLE
animation property doesn't transform correctly

### ISSUE THREAD

**Issue by bloodyowl** [webpack/css-loader#65]
only the first part of the value is transformed:

``` css
animation: 300ms ease-in-out myAnimation;
```

is transformed to

``` css
animation: [hash] ease-in-out myAnimation;
```

**Comment by ArekBartnik** [comment]
Is there any quick fix for this?

**Comment by egoens** [comment]
I'm having the same issue. Attempted to adjust the order of animation attrs but nothing seems to fix this issue. We had to jam in a hack that puts the animation into a `:global` wrapper in order to get it to work.

```
:global {
    animation: 3s opacity infinite;
}
```

**Comment by d3viant0ne** [comment]
@bloodyowl @egoens - Is this still an issue on `v0.26.1`

**Comment by egoens** [comment]
Not sure @d3viant0ne. We've since moved to `styled-components` to drive our styles. Sorry I can't be of assistance.

**Comment by d3viant0ne** [comment]
No worries, just wanted to check in and be sure before I tagged it or closed it. I'll give it a few days for @bloodyowl to respond.

**Comment by bloodyowl** [comment]
Quite the same here, using CSS-in-JS now 🤷‍♂️
