### ISSUE TITLE
Locals and ExtractTextPlugin

### ISSUE THREAD

**Issue by vjpr** [webpack/css-loader#71]
When I use local-scoped vars the `require` statement returns the selector names.

But when I use the `ExtractTextPlugin`, the selectors are no longer returned.

Should `ExtractTextPlugin` pass through the selectors hash from `css-loader`?

**Comment by vjpr** [comment]
@sokra Can you confirm your example works here: https://github.com/webpack/css-loader/issues/59#issuecomment-109793167

**Comment by sokra** [comment]
This should work. I already done it here: https://github.com/webpack/react-starter

**Comment by vjpr** [comment]
If I set `{remove: false}` in the extract text loader, the require statement returns an object, with my selector in `{locals: {...}}`. The return value from the require should be just the contents of locals (or at least it is without ExtractText`.

**Comment by vjpr** [comment]
Hold on, my plugin is very out of date. Let me try upgrade.

**Comment by vjpr** [comment]
Fixed. Was on v0.3 of the extract text plugin. Sorry!
