### ISSUE TITLE
Disable local scoping for external libraries (node_modules)

### ISSUE THREAD

**Issue by bogdansoare** [webpack/css-loader#75]
First I want to say local scope enabled by defalut is amazing. (css-loader?module)

But I'm having trouble with third party libs when I import their css from node_modules. I don't want that css locally scoped, I want their css to be global.

For example when I try to use  [React Toggle](https://github.com/instructure-react/react-toggle) by importing @import "../../node_modules/react-toggle/style.css"; in my general shared css, each class gets scoped  with the localIdentName.

Any solutions? Thank you.

**Comment by zxcabs** [comment]
You can add `node_modules` in `exclude` options for loader.

**Comment by bogdansoare** [comment]
@zxcabs Thanks for the suggestion.

I ended up using 2 different loaders, one for the scoped components and another for the general shared css.

```javascript
{ test: /\.css$/, loader: ExtractTextPlugin.extract('css-loader?module&localIdentName=[name]__[local]!cssnext-loader'), include: /src\/components/ },
{ test: /\.css$/, loader: ExtractTextPlugin.extract('css-loader!cssnext-loader'), exclude: /src\/components/ },
```
