### ISSUE TITLE
Find a way to reuse postcss instance

### ISSUE THREAD

**Issue by MoOx** [webpack/css-loader#82]
Since you switched to postcss that would be nice to be able to use some plugins (like for example cssnext) via your module instead of duplicate parsing via another loader.
Are you open to that kind of enhancement ? That should not be a big deal to handle that right ?

**Comment by sokra** [comment]
I'm not sure if I would like to expose the PostCSS stuff from the css-loader. It's an implenentation detail. It's propably not a big performance issue... is it?

**Comment by MoOx** [comment]
Not sure it's a big one, but if we can avoid that...
What about just adding a `plugins` options (an array) that accept multiple plugin that you can pipe using (.use()) in your module ? That's should be quick and you don't really expose anything ?

**Comment by magsout** [comment]
it's a great idea, especially thanks to postcss that we can use the many plugins, including cssnext.

:+1:

**Comment by sokra** [comment]
> That's should be quick and you don't really expose anything ?

This would expose it.

For now I'll keep it hidden. So you need the postcss-loader in addition to the css-loader for postcss plugins. That isn't so complex or inperformant.

**Comment by MoOx** [comment]
What are you afraid of ?

**Comment by MoOx** [comment]
Indeed it's not complex. But that would be a sweet possible optimisation. And there is no small optimisation, there is just optimisations ^^

**Comment by markdalgleish** [comment]
I agree with @sokra. PostCSS shouldn't be exposed as part of the public
API. It's private implementation detail that we might want to move away
from in the future. Allowing users to couple themselves to our internal
technology choices makes it harder for us to manage change going forwards.
