### ISSUE TITLE
css-loader 0.15.1 breaking multiple transforms

### ISSUE THREAD

**Issue by kylecesmat** [webpack/css-loader#88]
#### Problem

Updated to the latest css-loader in my project and had issues with declarations where I had multiple transforms happening. Here is an example:

`transform: translate(-50%, -50%) scale(1,1);`

This would then be compiled to:
`transform: translate(-50%, -50% scale(1,1));`

I tried troubleshooting with newer/older versions of `style-loader`, `sass-loader`, `postcss-loader` etc and the only solution that worked was to revert css-loader back to 0.14.5.

Only thing that I changed from my initial config was updating css-loader to the latest and it broke. Might be related to #87?

**Comment by wmonk** [comment]
+1 for this issue. Also discovered it yesterday. I'm running version 0.15.1 too.

**Comment by markdalgleish** [comment]
I can't reproduce this issue. I tried adding your transform example to https://github.com/css-modules/webpack-demo and it compiled fine. Can you update your dependencies and verify you're still experiencing this?

**Comment by wmonk** [comment]
@markdalgleish is working for me now... quick sample of dependencies that are now working: 

```
├─┬ css-loader@0.15.1
│ ├── css-selector-tokenizer@0.5.2
│ ├── cssnano@1.4.3
│ ├── loader-utils@0.2.10
│ ├── postcss@4.1.13
│ ├── postcss-modules-extract-imports@0.0.5
│ ├── postcss-modules-local-by-default@0.0.10
│ ├── postcss-modules-scope@0.0.7
│ └── source-list-map@0.1.5
```
It doesn't look like anything has actually been updated in the time between my last comment and now. I tried adding to tests in `css-loader` and `postcss` but could never recreate it there either.

**Comment by d3viant0ne** [comment]
If this is still an issue on `v0.26.1` (i'm guessing not) please open a new issue and reference this one.
