### ISSUE TITLE
Use PostCSS async API

### ISSUE THREAD

**Issue by ai** [webpack/css-loader#95]
`css-loader` [uses](https://github.com/webpack/css-loader/blob/f0f7108a91ba1d09466fea4f2c8ccfbeb8d99d77/lib/processCss.js#L183) sync API for PostCSS.

It is restricted by [PostCSS Runner Guielines](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md), because you can’t use sync API with async plugins.

/cc @markdalgleish

**Comment by ai** [comment]
For example, cssnano can start to use async plugin.

**Comment by isairz** [comment]
I setup webpack config following example.
https://github.com/emmenko/redux-react-router-async-example

This example occurs same errer. I think this is a good test case for this issue.

**Comment by ai** [comment]
Seems like `cssnext-loader` also uses sync API

**Comment by MoOx** [comment]
FYI, I am responsible of the current shit https://github.com/postcss/postcss/issues/412#issuecomment-119307729

**Comment by sokra** [comment]
Thanks for the hint. We should use the async API...

**Comment by timdorr** [comment]
[cssnano v3.0.0 is out](https://github.com/ben-eb/cssnano/releases/tag/v3.0.0) and requires usage of the async API. So, this is now a reality :wink:
