### ISSUE TITLE
Adopt css-modules/css-modules-loader-core?

### ISSUE THREAD

**Issue by rtsao** [webpack/css-loader#98]
Any plans to adopt https://github.com/css-modules/css-modules-loader-core for the core css-modules functionality?

**Comment by joezimjs** [comment]
Currently css-modules-loader-core isn't working on Windows. I've tried working with them a little bit to help with that, but I haven't heard anything from them for a while and it's still not working.

**Comment by d3viant0ne** [comment]
@rtsao - Is this still an enhancement that you would like to have considered or can I close this issue?

**Comment by rtsao** [comment]
We can close it 👍

**Comment by d3viant0ne** [comment]
Perfect, thanks @rtsao
